### PR TITLE
Add README (rename the original README to requirements)

### PR DESCRIPTION
**Pull request by kaleocheng**
Sorry for the delay, I have been most of the work, there are some work in progress:
- the automated task to run the create script.
- the automated task to auto update the served sites.

### CODE REVIEW

**Comment by kaleocheng** [comment]
Now everything is done. @xuqingfeng

**Comment by xuqingfeng** [comment]
@kaleocheng Thanks for taking time to finish this test, we will evaluate and get back to you soon.

**Comment by kaleocheng** [comment]
@xuqingfeng  Hey Qingfeng, Has there been any progress?

**Comment by xuqingfeng** [comment]
Hi @kaleocheng , @zbal just came back from France, we will get back to you really soon.

By the way, what's your expected salary and when you will join us if we give you the offer? (You can reply to us by email)

**Comment by kaleocheng** [comment]
I'm looking forward to your feedback. I'll reply to the expected salary and entry time by email later today.

**Pull request closed without merging**
